FROM node:18-alpine AS base

WORKDIR /app

# Dependencies stage
COPY package*.json ./
RUN npm install

# Build stage
COPY . .
RUN npm run build

EXPOSE 3000

ENV PORT=3000
ENV NODE_ENV=production

CMD ["npm", "run", "start"]
